[2025-02-10T16:20:56.054+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T16:20:56.067+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_query_dag.update_query_task manual__2025-02-10T10:20:48.990469+00:00 [queued]>
[2025-02-10T16:20:56.073+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_query_dag.update_query_task manual__2025-02-10T10:20:48.990469+00:00 [queued]>
[2025-02-10T16:20:56.074+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T16:20:56.088+0600] {taskinstance.py:2889} INFO - Executing <Task(SQLExecuteQueryOperator): update_query_task> on 2025-02-10 10:20:48.990469+00:00
[2025-02-10T16:20:56.100+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'update_query_dag', 'update_query_task', 'manual__2025-02-10T10:20:48.990469+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/update_query.py', '--cfg-path', '/tmp/tmppbzm0rln']
[2025-02-10T16:20:56.101+0600] {standard_task_runner.py:105} INFO - Job 6: Subtask update_query_task
[2025-02-10T16:20:56.104+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=38944) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-10T16:20:56.104+0600] {standard_task_runner.py:72} INFO - Started process 39011 to run task
[2025-02-10T16:20:56.145+0600] {task_command.py:467} INFO - Running <TaskInstance: update_query_dag.update_query_task manual__2025-02-10T10:20:48.990469+00:00 [running]> on host shamim-X541UV
[2025-02-10T16:20:56.222+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='update_query_dag' AIRFLOW_CTX_TASK_ID='update_query_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T10:20:48.990469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T10:20:48.990469+00:00'
[2025-02-10T16:20:56.223+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-10T16:20:56.224+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-10T16:20:56.224+0600] {logging_mixin.py:190} INFO - Current task name:update_query_task state:running start_date:2025-02-10 10:20:56.067502+00:00
[2025-02-10T16:20:56.224+0600] {logging_mixin.py:190} INFO - Dag name:update_query_dag and current dag run status:running
[2025-02-10T16:20:56.224+0600] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T16:20:56.225+0600] {sql.py:295} INFO - Executing: 
    WITH avg_salaries AS(
    SELECT depertment, avg(salary) AS avg_salary FROM employees GROUP BY department)
    UPDATE employees
    SET salary=salary*2.2
    WHERE depertment IN(SELECT depertment from avg_salaries WHERE avg_salary<50000);
    
[2025-02-10T16:20:56.233+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-10T16:20:56.239+0600] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-02-10T16:20:56.287+0600] {sql.py:511} INFO - Running statement: 
    WITH avg_salaries AS(
    SELECT depertment, avg(salary) AS avg_salary FROM employees GROUP BY department)
    UPDATE employees
    SET salary=salary*2.2
    WHERE depertment IN(SELECT depertment from avg_salaries WHERE avg_salary<50000);
    , parameters: None
[2025-02-10T16:20:56.291+0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "depertment" does not exist
LINE 3:     SELECT depertment, avg(salary) AS avg_salary FROM employ...
                   ^
HINT:  Perhaps you meant to reference the column "employees.department".

[2025-02-10T16:20:56.322+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-10T16:20:56.322+0600] {logging_mixin.py:190} INFO - Task start:2025-02-10 10:20:56.067502+00:00 end:2025-02-10 10:20:56.321499+00:00 duration:0.253997
[2025-02-10T16:20:56.323+0600] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): update_query_task> dag:<DAG: update_query_dag> dagrun:<DagRun update_query_dag @ 2025-02-10 10:20:48.990469+00:00: manual__2025-02-10T10:20:48.990469+00:00, state:running, queued_at: 2025-02-10 10:20:49.071948+00:00. externally triggered: True>
[2025-02-10T16:20:56.323+0600] {logging_mixin.py:190} INFO - Failure caused by column "depertment" does not exist
LINE 3:     SELECT depertment, avg(salary) AS avg_salary FROM employ...
                   ^
HINT:  Perhaps you meant to reference the column "employees.department".
[2025-02-10T16:20:56.324+0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=update_query_dag, task_id=update_query_task, run_id=manual__2025-02-10T10:20:48.990469+00:00, execution_date=20250210T102048, start_date=20250210T102056, end_date=20250210T102056
[2025-02-10T16:20:56.339+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T16:20:56.339+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task update_query_task (column "depertment" does not exist
LINE 3:     SELECT depertment, avg(salary) AS avg_salary FROM employ...
                   ^
HINT:  Perhaps you meant to reference the column "employees.department".
; 39011)
Traceback (most recent call last):
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/shamim/airflow_git/Airflow_project/air_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "depertment" does not exist
LINE 3:     SELECT depertment, avg(salary) AS avg_salary FROM employ...
                   ^
HINT:  Perhaps you meant to reference the column "employees.department".

[2025-02-10T16:20:56.359+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-10T16:20:56.376+0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T16:20:56.377+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
